import * as React from 'react';
import lodash from 'lodash'

const MHello = () => {
    return <div>{ lodash.add(1,2)}MHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHelloMHello</div>
}

export default MHello